export const LOGIN_ERROR = "LOGIN_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_LOAD = "LOGIN_LOAD";

export const REGISTER_ERROR = "REGISTER_ERROR";
export const REGISTER_LOAD = "REGISTER_LOAD";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const LOGOUT = "LOGOUT";

export const SET_MESSAGE = "SET_MESSAGE";
export const CLEAR_MESSAGE = "CLEAR_MESSAGE";

export const GET_DATA_NFT_ERROR = "GET_DATA_NFT_ERROR";
export const GET_DATA_NFT_LOAD = "GET_DATA_NFT_LOAD";
export const GET_DATA_NFT_SUCCESS = "GET_DATA_NFT_SUCCESS";

export const REFRESH_TOKEN = "REFRESH_TOKEN";
